In [421]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [422]:
data = pd.read_csv('imdb_top_1000.csv')

In [423]:
data.info()
data.head()
data.describe()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Poster_Link    1000 non-null   object 
 1   Series_Title   1000 non-null   object 
 2   Released_Year  1000 non-null   object 
 3   Certificate    899 non-null    object 
 4   Runtime        1000 non-null   object 
 5   Genre          1000 non-null   object 
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object 
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object 
 10  Star1          1000 non-null   object 
 11  Star2          1000 non-null   object 
 12  Star3          1000 non-null   object 
 13  Star4          1000 non-null   object 
 14  No_of_Votes    1000 non-null   int64  
 15  Gross          831 non-null    object 
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB


Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [424]:
data.dropna(inplace=True)
print(data.isnull().sum())
data.head()

Poster_Link      0
Series_Title     0
Released_Year    0
Certificate      0
Runtime          0
Genre            0
IMDB_Rating      0
Overview         0
Meta_score       0
Director         0
Star1            0
Star2            0
Star3            0
Star4            0
No_of_Votes      0
Gross            0
dtype: int64


Poster_Link  \
0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   
3    The Godfather: Part II          1974           A  202 min   
4              12 Angry Men          1957           U   96 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   
3          Crime, Drama          9.0   
4          Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   
3  The early life and career of Vito Corleone in ...        90.0   
4  A jury holdout attempts to prevent a miscarria...        96.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   
3  Francis Ford Coppola       Al Pacino  Robert De Niro  Robert Duvall   
4          Sidney Lumet     Henry Fonda     Lee J. Cobb  Martin Balsam   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444  
3    Diane Keaton      1129952   57,300,000  
4    John Fiedler       689845    4,360,000

In [425]:
data.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [426]:
data = data.rename(columns={'Series_Title': 'Title', 'IMDB_Rating': 'Rating', 'Meta_score': 'Score'})
movies = data[['Title', 'Genre', 'Rating', 'Score', 'Overview', 'Star1', 'Star2', 'Star3', 'Star4', 'Director']]

In [427]:
movies.head()

Title                 Genre  Rating  Score  \
0  The Shawshank Redemption                 Drama     9.3   80.0   
1             The Godfather          Crime, Drama     9.2  100.0   
2           The Dark Knight  Action, Crime, Drama     9.0   84.0   
3    The Godfather: Part II          Crime, Drama     9.0   90.0   
4              12 Angry Men          Crime, Drama     9.0   96.0   

                                            Overview           Star1  \
0  Two imprisoned men bond over a number of years...     Tim Robbins   
1  An organized crime dynasty's aging patriarch t...   Marlon Brando   
2  When the menace known as the Joker wreaks havo...  Christian Bale   
3  The early life and career of Vito Corleone in ...       Al Pacino   
4  A jury holdout attempts to prevent a miscarria...     Henry Fonda   

            Star2          Star3           Star4              Director  
0  Morgan Freeman     Bob Gunton  William Sadler        Frank Darabont  
1       Al Pacino     James Caan    Diane Keaton  Francis Ford Coppola  
2    Heath Ledger  Aaron Eckhart   Michael Caine     Christopher Nolan  
3  Robert De Niro  Robert Duvall    Diane Keaton  Francis Ford Coppola  
4     Lee J. Cobb  Martin Balsam    John Fiedler          Sidney Lumet

In [428]:
import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/deprave/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/deprave/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/deprave/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/deprave/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [429]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = re.sub(r'[^\w\s]', '', text, re.UNICODE)
    text = text.lower()
    
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
    
    text = " ".join(lemmatized_tokens)
    return text

In [430]:
movies = movies.assign(
    metadata=movies['Genre'] + ' ' + 
             movies['Overview'] + ' ' + 
             movies['Star1'] + ' ' + 
             movies['Director']
)

In [431]:
movies['metadata'] = movies['metadata'].apply(clean_text)
movies.head()

Title                 Genre  Rating  Score  \
0  The Shawshank Redemption                 Drama     9.3   80.0   
1             The Godfather          Crime, Drama     9.2  100.0   
2           The Dark Knight  Action, Crime, Drama     9.0   84.0   
3    The Godfather: Part II          Crime, Drama     9.0   90.0   
4              12 Angry Men          Crime, Drama     9.0   96.0   

                                            Overview           Star1  \
0  Two imprisoned men bond over a number of years...     Tim Robbins   
1  An organized crime dynasty's aging patriarch t...   Marlon Brando   
2  When the menace known as the Joker wreaks havo...  Christian Bale   
3  The early life and career of Vito Corleone in ...       Al Pacino   
4  A jury holdout attempts to prevent a miscarria...     Henry Fonda   

            Star2          Star3           Star4              Director  \
0  Morgan Freeman     Bob Gunton  William Sadler        Frank Darabont   
1       Al Pacino     James Caan    Diane Keaton  Francis Ford Coppola   
2    Heath Ledger  Aaron Eckhart   Michael Caine     Christopher Nolan   
3  Robert De Niro  Robert Duvall    Diane Keaton  Francis Ford Coppola   
4     Lee J. Cobb  Martin Balsam    John Fiedler          Sidney Lumet   

                                            metadata  
0  drama two imprisoned men bond number year find...  
1  crime drama organized crime dynasty aging patr...  
2  action crime drama menace known joker wreaks h...  
3  crime drama early life career vito corleone 19...  
4  crime drama jury holdout attempt prevent misca...

In [432]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['metadata'])

scaler = MinMaxScaler()
movies[['Rating', 'Score']] = scaler.fit_transform(movies[['Rating', 'Score']])

numerical_features = movies[['Rating', 'Score']]
numerical_similarity = cosine_similarity(numerical_features, numerical_features)

text_similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)


In [433]:
numerical_similarity

array([[1.        , 0.98196514, 0.99138605, ..., 0.58549055, 0.58549055,
        0.58549055],
       [0.98196514, 1.        , 0.9982684 , ..., 0.72819999, 0.72819999,
        0.72819999],
       [0.99138605, 0.9982684 , 1.        , ..., 0.68662353, 0.68662353,
        0.68662353],
       ...,
       [0.58549055, 0.72819999, 0.68662353, ..., 1.        , 1.        ,
        1.        ],
       [0.58549055, 0.72819999, 0.68662353, ..., 1.        , 1.        ,
        1.        ],
       [0.58549055, 0.72819999, 0.68662353, ..., 1.        , 1.        ,
        1.        ]])

In [434]:
text_similarity

array([[1.        , 0.00312117, 0.00272461, ..., 0.        , 0.        ,
        0.00301806],
       [0.00312117, 1.        , 0.02215945, ..., 0.        , 0.        ,
        0.00297383],
       [0.00272461, 0.02215945, 1.        , ..., 0.        , 0.        ,
        0.00259599],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.02173295,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.02173295, 1.        ,
        0.        ],
       [0.00301806, 0.00297383, 0.00259599, ..., 0.        , 0.        ,
        1.        ]])

In [435]:
alpha = 0.8
beta = 1 - alpha

combined_similarity = (alpha * numerical_similarity) + (beta * text_similarity)

In [436]:
combined_similarity

array([[1.        , 0.78619635, 0.79365377, ..., 0.46839244, 0.46839244,
        0.46899606],
       [0.78619635, 1.        , 0.80304661, ..., 0.58255999, 0.58255999,
        0.58315476],
       [0.79365377, 0.80304661, 1.        , ..., 0.54929883, 0.54929883,
        0.54981802],
       ...,
       [0.46839244, 0.58255999, 0.54929883, ..., 1.        , 0.80434659,
        0.8       ],
       [0.46839244, 0.58255999, 0.54929883, ..., 0.80434659, 1.        ,
        0.8       ],
       [0.46899606, 0.58315476, 0.54981802, ..., 0.8       , 0.8       ,
        1.        ]])

In [437]:
def recommend(title, combined_similarity=combined_similarity, top_n=10):
    idx = movies[movies['Title'] == title].index[0]
    
    sim_scores = list(enumerate(combined_similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]
    movie_indices = [i[0] for i in sim_scores]
    return movies['Title'].iloc[movie_indices]

In [438]:
example = 'The Dark Knight'
recommend(example)

155             Batman Begins
63      The Dark Knight Rises
36               The Prestige
33                      Joker
21               Interstellar
8                   Inception
272      Pink Floyd: The Wall
96                     Snatch
42                       Léon
3      The Godfather: Part II
Name: Title, dtype: object

In [439]:
import pickle

with open('combined_similarity.pkl', 'wb') as f:
    pickle.dump(combined_similarity, f)

In [440]:
movies.to_csv('movies.csv', index=False)